on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 Windows
    runs-on: windows-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Deploy files via SSH
        env: 
          SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
          REMOTE_HOST: ${{secrets.HOST}}
          REMOTE_USER: ${{secrets.USER}}
        run: |
          $keyFile = "$env:TEMP\key.pem"
          $remotePath = "/"
          
          Set-Content -Path $keyFile -Value $env:SSH_PRIVATE_KEY
          Set-Content -Path $env:TEMP\known_hosts -Value "$REMOTE_HOST ecdsa-sha2-nistp256 <HOST KEY HERE>"
          
          $scpOptions = "-o StrictHostKeyChecking=no -o UserKnownHostsFile=$env:TEMP\known_hosts"
          scp -i $keyFile $scpOptions -r .\* "$REMOTE_USER@$REMOTE_HOST:$remotePath"
          ssh -i $keyFile $scpOptions "$REMOTE_USER@$REMOTE_HOST" "cd $remotePath ; Expand-Archive -Force files_to_copy.zip . ; Start-Process -NoNewWindow -FilePath 'C:\'"
