on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 Windows
    runs-on: windows-latest

    steps:
    - name: Checkout the files
      uses: actions/checkout@v2

    - name: Create and Copy files with SSH
      env: 
        SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
        REMOTE_HOST: ${{secrets.HOST}}
        REMOTE_USER: ${{secrets.USER}}
      run: |
        New-Item -Path $env:USERPROFILE\.ssh -ItemType Directory -Force
        Set-Content -Path $env:USERPROFILE\.ssh\id_rsa -Value $env:SSH_PRIVATE_KEY
        chmod 600 $env:USERPROFILE\.ssh\id_rsa

        ssh-keyscan -H $env:REMOTE_HOST | Out-File -Append -Encoding utf8 $env:USERPROFILE\.ssh\known_hosts
        chmod 644 $env:USERPROFILE\.ssh\known_hosts

        $TEMP_DIR = New-TemporaryFile -Directory
        Copy-Item -Recurse -Path .\* -Destination $TEMP_DIR.FullName
        cd $TEMP_DIR.FullName
        Compress-Archive -Path .\* -DestinationPath files_to_copy.zip

        scp -i $env:USERPROFILE\.ssh\id_rsa -o StrictHostKeyChecking=no files_to_copy.zip $env:REMOTE_USER@$env:REMOTE_HOST:/path/to/destination

        ssh -i $env:USERPROFILE\.ssh\id_rsa -o StrictHostKeyChecking=no $env:REMOTE_USER@$env:REMOTE_HOST "cd /path/to/destination ; Expand-Archive -Force files_to_copy.zip ."

        # Execute os comandos adicionais para iniciar a aplicação no Windows
        ssh -i $env:USERPROFILE\.ssh\id_rsa -o StrictHostKeyChecking=no $env:REMOTE_USER@$env:REMOTE_HOST "cd /path/to/destination ; Start-Process -NoNewWindow -FilePath 'C:\path\to\your\executable.exe'"

        Remove-Item -Path $TEMP_DIR.FullName -Recurse -Force