on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 Windows
    runs-on: windows-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Deploy files via SSH
        env: 
          SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
          REMOTE_HOST: ${{secrets.HOST}}
          REMOTE_USER: ${{secrets.USER}}
          TARGET: "/c/Users"
