on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the files
      uses: actions/checkout@v3

    - name: Create and Copy files with SSH
      env: 
        SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
        REMOTE_HOST: ${{secrets.HOST}}
        REMOTE_USER: ${{secrets.USER}}
      run: |
        mkdir -p ~/.ssh  # Create the .ssh directory if it doesn't exist
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

        # Create a temporary directory to store the files to be copied
        TEMP_DIR=$(mktemp -d)

        # Copy the necessary files to the temporary directory
        cp -r ./ $TEMP_DIR/

        # Compress the files into a zip archive
        cd $TEMP_DIR
        zip -r files_to_copy.zip .

        # Copy the zip archive to the remote host's PedalHubApi directory
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no files_to_copy.zip $REMOTE_USER@$REMOTE_HOST:/home/ec2-user/PedalHubApi/

        # Connect to the remote host and extract the files from the zip archive
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "cd /home/ec2-user/PedalHubApi && unzip -o files_to_copy.zip"

        # Clean up - remove the temporary directory and zip archive
        rm -rf $TEMP_DIR
