name: Push-to-EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the files
      uses: actions/checkout@v3

    - name: Copy files with SSH
      env: 
        SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
        REMOTE_HOST: ${{secrets.HOST}}
        REMOTE_USER: ${{secrets.USER}}
      run: |
        mkdir -p /home/ec2-user/PedalHubApi
        echo "$SSH_PRIVATE_KEY" > ssh_key.pem
        chmod 600 ssh_key.pem
        scp -i ssh_key.pem -o StrictHostKeyChecking=no -r ./ ec2-user@$REMOTE_HOST:/home/ec2-user/PedalHubApi
